import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

import { resolveStylesPath } from "./project.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

const PRESET_DESCRIPTIONS: Record<string, string> = {
  blue: "Default — blue, teal, fuchsia, violet, gray",
  sunset: "Warm — orange, rose, amber, pink, stone",
  forest: "Natural — emerald, lime, teal, green, stone",
  ocean: "Cool — sky, cyan, indigo, teal, slate",
  berry: "Vibrant — purple, pink, fuchsia, violet, rose",
  mono: "Minimal — zinc monochrome",
};

/**
 * Fences the generated block inside `styles.css` so re-applying a preset
 * replaces it instead of stacking, while leaving the user's own overrides
 * (which live in the same file) untouched.
 */
const BEGIN_MARKER = "/* vantage-template:chart-preset — regenerated by `chart`; edits here are lost */";
const END_MARKER = "/* vantage-template:chart-preset:end */";

export function getChartPresetsDir(): string {
  return join(__dirname, "..", "chart-presets");
}

export function listChartPresetNames(): string[] {
  const dir = getChartPresetsDir();
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".css"))
    .map((f) => f.replace(/\.css$/, ""))
    .sort();
}

export function getChartPresetDescription(name: string): string {
  return PRESET_DESCRIPTIONS[name] ?? "";
}

export function getChartPresetPath(name: string): string {
  return join(getChartPresetsDir(), `${name}.css`);
}

export interface ApplyChartPresetOptions {
  dryRun?: boolean;
}

export interface ApplyChartPresetResult {
  targetPath: string;
  content: string;
}

/**
 * Write the preset's `--chart-*` tokens into the project's `styles.css`.
 *
 * A Vantage app has no theme file of its own — the framework owns `theme.css`
 * and auto-imports `styles.css` after it, so overriding the tokens there is the
 * supported way to restyle charts.
 *
 * Since `@squadbase/vantage` v0.3.0 that file sits next to the pages, so it is
 * `src/styles.css` in a `src/` project and `styles.css` otherwise.
 */
export function applyChartPreset(
  projectRoot: string,
  presetName: string,
  options: ApplyChartPresetOptions = {},
): ApplyChartPresetResult {
  const presetPath = getChartPresetPath(presetName);
  if (!existsSync(presetPath)) {
    throw new Error(`Chart preset "${presetName}" not found.`);
  }

  const targetPath = resolveStylesPath(projectRoot);
  if (!existsSync(targetPath)) {
    throw new Error(`${relative(projectRoot, targetPath)} not found in project.`);
  }

  const preset = readFileSync(presetPath, "utf-8").trimEnd();
  const block = `${BEGIN_MARKER}\n${preset}\n${END_MARKER}\n`;

  const current = readFileSync(targetPath, "utf-8");
  const begin = current.indexOf(BEGIN_MARKER);
  const end = current.indexOf(END_MARKER);

  let content: string;
  if (begin !== -1 && end !== -1) {
    content = current.slice(0, begin) + block + current.slice(end + END_MARKER.length + 1);
  } else {
    content = `${current.trimEnd()}\n\n${block}`;
  }

  if (!options.dryRun) {
    writeFileSync(targetPath, content, "utf-8");
  }

  return { targetPath, content };
}
