import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const appDir = join(root, "..", "vantage");
const chartPresetsDir = join(root, "chart-presets");

export const devDir = join(root, "dev");
export const uiTemplatesDir = join(root, "ui-templates");

// Kept in sync with `applyChartPreset` in src/chart-presets.ts — the dev copy
// writes the same fenced block so a preset previewed here matches what the CLI
// would produce in a real project.
const CHART_BEGIN_MARKER =
  "/* vantage-template:chart-preset — regenerated by `chart`; edits here are lost */";
const CHART_END_MARKER = "/* vantage-template:chart-preset:end */";

export function listUiTemplateNames() {
  if (!existsSync(uiTemplatesDir)) return [];
  return readdirSync(uiTemplatesDir)
    .filter((d) => existsSync(join(uiTemplatesDir, d, "manifest.json")))
    .sort();
}

function listChartPresetNames() {
  if (!existsSync(chartPresetsDir)) return [];
  return readdirSync(chartPresetsDir)
    .filter((f) => f.endsWith(".css"))
    .map((f) => f.replace(/\.css$/, ""))
    .sort();
}

/**
 * Build `dev/` — a throwaway copy of the base Vantage app (`../vantage/`) with
 * one ui-template applied — and return where it landed.
 *
 * The app is rsynced fresh on every call, so files left behind by a previously
 * previewed template are removed rather than piling up as dead routes.
 *
 * Template files are **copied, not symlinked**: Vantage's route scan treats a
 * symlink as neither file nor directory, so a symlinked `src/index.tsx` is
 * skipped entirely and `/` renders the 404 page. `dev.mjs` re-copies on change
 * to get live editing back.
 */
export function setupDev(templateName, { chartPreset } = {}) {
  const name = templateName ?? listUiTemplateNames()[0];
  if (!name) throw new Error("No template found in ui-templates/");

  if (chartPreset) {
    const available = listChartPresetNames();
    if (!available.includes(chartPreset)) {
      throw new Error(
        `Chart preset "${chartPreset}" not found. Available: ${available.join(", ")}`,
      );
    }
  }

  const manifestPath = join(uiTemplatesDir, name, "manifest.json");
  if (!existsSync(manifestPath)) {
    throw new Error(`Template not found in ui-templates/: ${name}`);
  }

  if (!existsSync(appDir)) {
    throw new Error(`Base app not found at ${appDir}`);
  }

  // node_modules is excluded so the symlink planted below survives --delete.
  execSync(
    "rsync -a --delete --exclude='node_modules' --exclude='dist' --exclude='.vantage' --exclude='package-lock.json' --exclude='*.tsbuildinfo' --exclude='*.log' ../vantage/ dev/",
    { cwd: root, stdio: "inherit" },
  );

  const devModules = join(devDir, "node_modules");
  if (!existsSync(devModules)) {
    if (!existsSync(join(appDir, "node_modules"))) {
      throw new Error(
        "../vantage/node_modules not found. Run `npm install` in ../vantage/ first.",
      );
    }
    symlinkSync(join("..", "..", "vantage", "node_modules"), devModules);
  }

  const manifest = JSON.parse(readFileSync(manifestPath, "utf-8"));
  const files = manifest.files.map((file) => {
    const srcPath = join(uiTemplatesDir, name, file.src);
    if (!existsSync(srcPath)) {
      throw new Error(`${name}: manifest lists ${file.src}, which does not exist`);
    }
    // Mirrors `resolveDest` in src/project.ts. Manifest dests are relative to
    // the page-scan root; only `scope: "root"` entries (server/, public/) sit at
    // the project root. dev/ is an rsync of ../vantage/, which has src/.
    const destRel = file.scope === "root" ? file.dest : join("src", file.dest);
    return { srcPath, destPath: join(devDir, destRel) };
  });

  for (const { srcPath, destPath } of files) {
    copyTemplateFile(srcPath, destPath);
  }

  if (chartPreset) {
    applyChartPreset(chartPreset);
  }

  return { devDir, templateName: name, chartPreset: chartPreset ?? null, files };
}

/**
 * Path to the CLI inside `dev/`. Callers must spawn this rather than `npx
 * vantage` — the npm wrapper swallows SIGTERM, leaving orphaned dev servers.
 */
export function vantageBin() {
  return join(devDir, "node_modules", ".bin", "vantage");
}

export function copyTemplateFile(srcPath, destPath) {
  mkdirSync(dirname(destPath), { recursive: true });
  copyFileSync(srcPath, destPath);
}

function applyChartPreset(presetName) {
  const preset = readFileSync(
    join(chartPresetsDir, `${presetName}.css`),
    "utf-8",
  ).trimEnd();
  const block = `${CHART_BEGIN_MARKER}\n${preset}\n${CHART_END_MARKER}\n`;

  // v0.3.0+ keeps styles.css next to the pages, and the base app has src/.
  const targetPath = join(devDir, "src", "styles.css");
  const current = readFileSync(targetPath, "utf-8");
  writeFileSync(targetPath, `${current.trimEnd()}\n\n${block}`, "utf-8");
}
